# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LikelihoodMDP <- function(y_rcpp, y_lagged_rcpp, x_rcpp, z_rcpp, alpha_rcpp, mu_rcpp, sigma_rcpp, rho_rcpp, beta_rcpp, gamma_rcpp) {
    .Call('mixPanel_LikelihoodMDP', PACKAGE = 'mixPanel', y_rcpp, y_lagged_rcpp, x_rcpp, z_rcpp, alpha_rcpp, mu_rcpp, sigma_rcpp, rho_rcpp, beta_rcpp, gamma_rcpp)
}

LikelihoodMDPInitialFixed <- function(y_rcpp, y_lagged_rcpp, x_rcpp, z_rcpp, alpha_rcpp, mu_rcpp, sigma_rcpp, rho_rcpp, beta_rcpp, gamma_rcpp) {
    .Call('mixPanel_LikelihoodMDPInitialFixed', PACKAGE = 'mixPanel', y_rcpp, y_lagged_rcpp, x_rcpp, z_rcpp, alpha_rcpp, mu_rcpp, sigma_rcpp, rho_rcpp, beta_rcpp, gamma_rcpp)
}

